### ISSUE TITLE
Unusable. Images Broken, layouts broken

### ISSUE THREAD

**Issue by jwetz87** [ycfreeman/wow-recruit-widget#1]
I have tried on two different installations of wordpress now, this plugin. It looks awesome on your site, it definitely would be something we'd use for our site. However, none of the sprites seem to be working (it links to the wrong file it looks like) but if you select huge icons, the whole plugin turns to text and nothing else.

**Comment by ycfreeman** [comment]
Hi can you specify what version if WordPress and php you're using? Thanks

**Comment by jwetz87** [comment]
Hey there. Wordpress 4.4.1 and PHP 5.4.43.

To be a tad more detailed, the sprite image being linked to is easy enough
to fix (I believe) it's linking to sprite.36 or something but the code
seems to reference just sprite.jpg. Changing to "Huge Icons" literally
removes all styling and images from the entire widget and just leaves it
with a gray text, each item being on a separate line. None of the icon
displays links to the correct sprite.

**Comment by ycfreeman** [comment]
thank you for reporting, i'll look into it

**Comment by jwetz87** [comment]
Yep! No problem. The plugin honestly seems perfect for what we're wanting
for our site :). (I'm assuming you can use multiple instances of it
however) either way, thought you'd like to know it's seemingly not working.

All the images seem to not work btw. Like even on the backend, there is a
broken image inserted for the "report bug" button and "more info". Not sure
if that helps or not.
